name: seonbi
version: 0.4.0
synopsis: SmartyPants for Korean language
category: Text
author: Hong Minhee <hong.minhee@gmail.com>
maintainer: Hong Minhee <hong.minhee@gmail.com>
copyright: "\xa9 2018\u20132023 Hong Minhee"
license: LGPL-2.1
homepage: https://github.com/dahlia/seonbi
bug-reports: https://github.com/dahlia/seonbi/issues
git: git://github.com/dahlia/seonbi.git
description:
  Please see the README.md on GitHub at <https://github.com/dahlia/seonbi>.
extra-source-files:
- src/Text/Seonbi/Unihan/*.json
- CHANGES.md
- README.md
data-dir: data
data-files:
- '*.tsv'
build-type: Custom
custom-setup:
  dependencies:
  - base
  - bytestring
  - Cabal
  - directory >= 1 && < 2
  - filepath
  - http-client >= 0.5 && < 0.8
  - temporary >= 1.2 && < 1.4
  - text
  - zip >= 1.1 && < 1.8
dependencies:
- aeson >= 1.3.1 && < 3
- base >= 4.12 && < 5
- bytestring
- containers
- html-entities >= 1 && < 2
- text
flags:
  static:
    description: Static link
    manual: true
    default: false
  iconv:
    description: Use iconv; however it is ignored on Windows
    manual: true
    default: false
  embed-dictionary:
    description: Embed dictionary rather than load from file
    manual: true
    default: false
when:
- condition: os(darwin)
  else:
    ghc-options:
    - -Wall
    - -fprint-explicit-kinds
  then:
    ghc-options:
    - -Wall
    - -fprint-explicit-kinds
    - -optP-Wno-nonportable-include-path
    # The above option works around https://github.com/haskell/cabal/issues/4739
library:
  source-dirs: src
  dependencies:
  - attoparsec >= 0.12 && < 1
  - bytestring-trie >= 0.2.5 && < 0.3
  - cassava >= 0.5 && < 0.6
  - cmark >= 0.6 && < 1
  - data-default >= 0.2 && < 1
  - filepath >= 1 && < 2
  - file-embed >= 0.0.10 && < 0.0.16
  - http-media >= 0.8 && < 1
  when:
  - condition: flag(static) || flag(embed-dictionary)
    then:
      cpp-options:
      - -DEMBED_DICTIONARY
    else:
      cpp-options:
      - -DNO_EMBED_DICTIONARY
executables:
  seonbi:
    main: seonbi.hs
    source-dirs: app
    when:
    - condition: flag(iconv) && !os(windows)
      else:
        dependencies: &executable-seonbi-dependencies
          cases: ">= 0.1.3.2 && < 0.1.5"
          html-charset: ">= 0.1 && < 0.2"
          optparse-applicative: ">= 0.14 && < 0.18"
          seonbi: ">= 0"
      then:
        dependencies:
          <<: *executable-seonbi-dependencies
          iconv: ">= 0.4 && < 0.5"
        cpp-options:
        - -DICONV
    - &executable-ghc-options
      condition: flag(static)
      then:
        when:
        - condition: os(darwin) || os(windows)
          then:
            ghc-options:
            - -Wall
            - -fwarn-incomplete-uni-patterns
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            # Static link
            - -static
            - -optc-Os
          else:
            ghc-options:
            - -Wall
            - -fwarn-incomplete-uni-patterns
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            # Static link
            - -static
            - -optl-static
            - -optl-pthread
            - -optc-Os
            - -fPIC
        ld-options:
        - -static
      else:
        ghc-options:
        - -Wall
        - -fwarn-incomplete-uni-patterns
        - -threaded
        - -rtsopts
        - -with-rtsopts=-N
  seonbi-api:
    main: seonbi-api.hs
    source-dirs: app
    dependencies:
    - http-types >= 0.12 && < 0.13
    - optparse-applicative >= 0.14 && < 0.18
    - seonbi
    - wai >= 3.2 && < 3.4
    - warp >= 3.2 && < 3.4
    when:
    - *executable-ghc-options
tests:
  doctest:
    main: doctest.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - doctest
    - doctest-discover
    - QuickCheck
    - seonbi
    - unicode-show
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Diff >= 0.3.4 && < 0.5
    - directory >= 1 && < 2
    - filepath >= 1 && < 2
    - hspec >= 2.4.8 && < 3
    - hspec-discover >= 2.4.8 && < 3
    - interpolatedstring-perl6 >= 1.0.1 && < 2
    - random >= 1.1 && < 1.3
    - seonbi
    - text
  hlint:
    main: hlint.hs
    source-dirs: test
    other-modules: []
    ghc-options:
    - -threaded
    dependencies:
    - hlint >= 2.1.7 && < 3.5
